const cat = {
	home: {
		title: "Inici",
		bottomBar: {
			map: "Mapa",
			vehicle: "Vehícle",
			bike: "Bici",
			favs: "Preferits",
			highlight: "Destacats",
		}, 
		searchBar: "Buscar:",
		car: "Cotxe",
		bike: "Bicicleta",
		foot: "A peu",
		time: "Temps estimat",
		distance: "Distància",
		routeOptions: "Opcions de ruta",
	}, 
	settings: {
		title: "Configuració",
		subtitle: "Benvingut a la configuració",
		logOut: "Tancar sessió",
		setEN: "Anglès",
		setCAT: "Català",
		setES: "Espanyol",
		deleteAccount: "Esborrar el teu compte",
		deleteAccountTitle: "Segur que vols esborrar el teu compte?",
		deleteAccountSubtitle: "Aquesta acció no és reversible i perdràs accés futur a l'aplicació.",
		setLanguage: "Escollir idioma",
		confirmDeleteAccount: "Per eliminar el teu compte cal escriure a sota el teu nom d'usuari",
	}, 
	signIn: {
		title: "Iniciar sessió",
		form: {
			enterCredentials: "Introdueix els credencials",
		}, 
		otherSocial: "O inicia sessió amb",
		pwdOrEmailMessage: "Hi ha un error amb el email o la contrasenya",
		emptyFieldMessage: "Siusplau ompli tots els camps",
		banMessage: "Aquest usuari es troba vetat de la app",
		noAccount: "No tens compte?",
		enterEmail: "Introdueix el teu email",
		enterPassword: "Introdueix la teva contrasenya",
	}, 
	signUp: {
		title: "Registrar-se",
		form: {
			enterCredentials: "Introdueix els credencials",
			email: "Email:",
			password: "Contrasenya:",
			name: "Nom:",
		}, 
		goToSignIn: "Anar a Inciar sessió",
		alreadyAccount: "Ja tens compte?",
		enterEmail: "Introdueix el teu email",
		enterPassword: "Introdueix la teva contrasenya",
		enterName: "Introdueix el teu nom",
	}, 
	miscelaneus: {
		loading: "Carregant...",
		cancel: "Cancel·lar",
		back: "Enrere",
		exit: "Sortir",
		accept: "Acceptar",
		delete: "Eliminar",
		vehicleWord: "vehicle",
	}, 
	vehicleConfig: {
		title: "Configuració del vehicle",
		vehicleBrand: "Marca del vehicle",
		vehicleBrandPlaceholder: "Introdueix la marca",
		vehicleModel: "Model del vehícle",
		vehicleModelPlaceholder: "Introdueix el model",
		vehicleNumPlate: "Matrícula",
		vehicleNumPlatePlaceholder: "Introdueix la matrícula",
		vehicleColor: "Color del vehicle",
		vehicleNickname: "Sobrenom del vehicle",
		vehicleNicknamePlaceholder: "Introdueix el sobrenom",
		continue: "Continua",
		notEV: "No tens un vehicle per afegir?",
		cancel: "Cancel·lar",
		skip: "Salta",
		customize: "Personalitza el teu",
		errorNumberPlate: "La matrícla ja existeix",
		defaultVehicle: "Aquest vehicle està marcat com a predeterminat.",
	}, 
	profile: {
		yourVehicle: "El teu garatge",
		changeVehicle: "Llisca per canviar el teu vehicle per defecte",
		title: "Perfil",
		vehicleNotDef: "Vehicle no definit",
		addNewVehicle: "Afegeix un vehicle",
		saveChanges: "Desa els canvis",
		deleteVehicle: "Segur que vols eliminar el teu vehicle?",
		editProfile: "Edita el teu perfil",
	}, 
	carInfoItem: {
		nickname: "Sobrenom:",
		numberPlate: "Matricula:",
	}, 
	drawer: {
		home: "Inici",
		profile: "Perfil",
		settings: "Configuració",
		tellAFriend: "Comparteix amb un amic!",
		logOut: "Tancar sessió",
		shareMessage: "Descobreix EcoRoads | Una aplicació per a planejar els teus viatges 'Eco-Friendly' de forma eficient.",
		achievements: "Assoliments",
		report: "Incidència",
		help: "Ajuda",
	}, 
	locationInfo: {
		mechanical: "Mecàniques",
		electrical: "Elèctriques",
		freeSlots: "Espais lliures",
		getThere: "Porta-m'hi!",
		likesNumber: "M'agrades",
		reportsNumber: "Incidències",
		report: "Reportar",
		pollutionLevel: "Contaminació:",
		shareStation: "Compartir",
		shareMessage: "Ei! Fes-li una ullada a",
		shareMessage2: ". Ens veiem allà!",
	}, 
	uploadImage: {
		editImage: "Editar Imatge",
		uploadImage: "Afegir Imatge",
	}, 
	achievementScreen: {
		subtitle: "Els teus assoliments:",
		shareMessage: "He completat aquest assoliment a EcoRoads. Fes-li una ullada: ",
		Achievements: {
			tellAFriendTitle: "Digues-li a un amic!",
			tellAFriendDescription: "Comparteix l'app amb un amic a través del menu lateral per a obtenir aquest assoliment.",
			firstRouteTitle: "Som-hi!",
			firstRouteDescription: "Selecciona una estació i clica 'Porta-m'hi!' per a obtenir aquest assoliment.",
			fiveRoutesTitle: "Som-hi!",
			fiveRoutesDescription: "Planeja cinc rutes amb el mapa de l'aplicació per a obtenir aquest assoliment.",
			twentyRoutesTitle: "Som-hi!",
			twentyRoutesDescription: "Planeja vint rutes amb el mapa de l'aplicació per a obtenir aquest assoliment.",
			firstSearchTitle: "On anem?",
			firstSearchDescription: "Cerca una estació amb la barra de cerca del mapa per a obtenir aquest assoliment.",
			fiveSearchesTitle: "On anem?",
			fiveSearchesDescription: "Cerca cinc estacions amb la barra de cerca del mapa per a obtenir aquest assoliment.",
			twentySearchesTitle: "On anem?",
			twentySearchesDescription: "Cerca vint estacions amb la barra de cerca del mapa per a obtenir aquest assoliment.",
			shareAStationTitle: "Ens veiem allà!",
			shareAStationDescription: "Comparteix una estació amb un amic seleccionant-la per a obtenir aquest assoliment.",
			shareFiveStationsTitle: "Ens veiem allà!",
			shareFiveStationsDescription: "Comparteix cinc estacions amb un amic seleccionant-les per a obtenir aquest assoliment.",
			shareTenStationsTitle: "Ens veiem allà!",
			shareTenStationsDescription: "Comparteix deu estacions amb un amic seleccionant-les per a obtenir aquest assoliment.",
			setStationAsFavouriteTitle: "T'escullo a tu!",
			setStationAsFavouriteDescription: "Selecciona una estació com a preferida seleccionant-la per a obtenir aquest assoliment.",
			setThreeStationsAsFavouriteTitle: "T'escullo a tu!",
			setThreeStationsAsFavouriteDescription: "Selecciona tres estacions com a preferides seleccionant-les per a obtenir aquest assoliment.",
			likeAStationTitle: "M'agrades. Té, una galeta.",
			likeAStationDescription: "Dona-li m'agrada a una estació seleccionant-la per a obtenir aquest assoliment.",
			likeFiveStationsTitle: "M'agrades. Té, una galeta.",
			likeFiveStationsDescription: "Dona-li m'agrada a cinc estacions seleccionant-les per a obtenir aquest assoliment.",
			likeTwentyStationsTitle: "M'agrades. Té, una galeta.",
			likeTwentyStationsDescription: "Dona-li m'agrada a vint estacions seleccionant-les per a obtenir aquest assoliment.",
		}, 
	}, 
	report: {
		ReportApplicationScreen: {
			fillfields: "Si us plau emplena tots els camps",
			OSversion: "Sistema Operatiu",
			subjectinquiry: "Tema de consulta",
			detailsinquiry: "Detalls de la consulta",
			title: "Pantalla d'Incidències",
			mobilepl: "Tipus de dispositiu",
			type: "Tipus de Incidència",
			smartphone: "Smartphone",
			tablet: "Tauleta",
			ios: "iOS",
			android: "Android",
			bug: "Bug",
			generalHelp: "Ajuda general",
			featureRequest: "Sol·licitud de funcionalitat",
			feedback: "Comentari",
		}, 
		send: "Enviar",
		reportStation: {
			title: "Reportar una estació",
			subtitle: "",
			placeholder: "Descripció del problema",
			poorCondition: "Males condicions",
			badInformation: "Informació errònia",
			dislike: "No m'agrada",
		}, 
	}, 
	achievementToast: {
		title: "Assoliment completat!",
	}, 
	reportToast: {
		title: "Incidència enviada",
		message: "S'ha enviat correctament l'incidència.",
		titleError: "Incidència no enviada",
		messageError: "Ja has enviat una incidència a aquesta estació.",
	}, 
	faq: {
		generalHelp: "Ajuda general",
		accountHelp: "Ajuda del compte",
		whatIsEcoroads: "Que és EcoRoads?",
		answerWhatIsEcoroads: "EcoRoads és una aplicació de mobilitat personal, que posa a la teva disposició informació i serveis per facilitar els teus viatges amb vehicles elèctrics.",
		moreServicesEcoroads: "Hi hauran més serveis dins d'EcoRoads?",
		answerMoreServicesEcoroads: "Sí, EcoRoads és una aplicació que estarà en constant creixement, amb la finalitat de poder oferir en tot moment el millor servei possible.",
		isThereCost: "Té algun cost utilitzar EcoRoads?",
		answerIsThereCost: "La descàrrega i ús de l'aplicació és completament gratuït.",
		personalizeMap: "Puc personalitzar el mapa?",
		answerPersonalizeMap: "Sí, pots filtrar fàcilment al mapa la informació dels punts de càrrega que vulguis en tot moment. A més pots afegir estacions a la teva secció de favorits i filtrar el mapa sobre la base d'aquests.",
		technicalIncidence: "Què faig si tinc una incidència tècnica?",
		answer1TechnicalIncidence: "Si es tracta d'una incidència tècnica relacionada amb algun punt de càrrega, podeu accedir al modal d'informació addicional d'aquesta estació per reportar directament el problema que tingueu.",
		answer2TechnicalIncidence: "Si es tracta d'una incidència tècnica de la pròpia aplicació, podeu accedir a la secció de reports de l'aplicació, situada a la barra de navegació lateral, per reportar la informació que veieu convenient.",
		mandatorySignIn: "És necessari registrar-se per utilitzar EcoRoads?",
		answerMandatorySignIn: "Sense un compte d'usuari no podràs accedir a les funcionalitats d'EcoRoads, per tant, és imprescindible que et registris.",
		safeData: "Estan segures les meves dades personals al sistema?",
		answerSafeData: "Sí, tota la informació està encriptada i compleix els estàndards de seguretat més exigents.",
		howToDelete: "Com dono de baixa el meu compte a EcoRoads?",
		answerHowToDelete: "Ho pots fer des de l'app, a la secció de configuració al perfil. Fent clic al botó d''Eliminar Compte', tota la teva informació s'eliminarà de la base de dades d'EcoRoads.",
	}, 
	onboarding: {
		title1: "Benvingut a Ecoroads",
		subtitle1: "L'aplicació per a planejar els teus viatges 'Eco-Friendly' de forma eficient",
		title2: "Personalitza el teu perfil",
		subtitle2: "Afegeix els teus vehicles i canvia el seu color al teu parer",
		title3: "Crea rutes fàcils de seguir",
		subtitle3: "Descobreix rutes que s'ajusten a la teva autonomía",
		title4: "Consulta la disponibilitat",
		subtitle4: "Coneix l'estat de qualsevol estació en temps real",
		title5: "Obté assoliments",
		subtitle5: "I comparteix-los amb els teus amics per a fardar-ne",
		skip: "Saltar",
		next: "Següent",
		done: "Finalitzar",
	}, 
	warningToast: {
		title: "Compte amb la contaminació",
		message: "Aquest destí té una contaminació de",
	}, 
	help: {
		chat: "Xat",
		faq: "FAQs",
		title: "Secció d'ajuda",
		tutorial: "Tutorial",
	}, 
	autonomyModal: {
		title: "Vols introduïr l'autonomia del teu vehicle?",
		placeholder: "La teva autonomia en km",
	}, 
	editProfile: {
		title: "Perfil actualitzat",
		message: "Els canvis s'han actualitzat correctament",
	}
}
export{ cat }