const en = {
	home: {
		title: "Home",
		bottomBar: {
			map: "Map",
			vehicle: "Vehicle",
			bike: "Bike",
			favs: "Favs",
			highlight: "Highlight",
		}, 
		searchBar: "Search:",
		car: "Car",
		bike: "Bike",
		foot: "On foot",
		time: "Estimated time",
		distance: "Distance",
		routeOptions: "Route options",
	}, 
	settings: {
		title: "Settings",
		subtitle: "Welcome to settings",
		logOut: "Log Out",
		setEN: "English",
		setCAT: "Catalan",
		setES: "Spanish",
		deleteAccount: "Delete your account",
		deleteAccountTitle: "Are you sure you want to delete you account?",
		deleteAccountSubtitle: "This action is not reversible and you will lose future access to the app.",
		setLanguage: "Set the language",
		confirmDeleteAccount: "To delete your account you must write down below your userame",
	}, 
	signIn: {
		title: "Log In",
		form: {
			enterCredentials: "Enter your credentials",
		}, 
		otherSocial: "Or Log In with",
		pwdOrEmailMessage: "There is an error with your password or email",
		emptyFieldMessage: "Please fill in all fields",
		banMessage: "This user has been banned from the app",
		noAccount: "Haven't got an account?",
		enterEmail: "Enter your email",
		enterPassword: "Enter your password",
	}, 
	signUp: {
		title: "Sign Up",
		form: {
			enterCredentials: "Enter your credentials",
			email: "Email:",
			password: "Password:",
			name: "Name:",
		}, 
		goToSignIn: "Go to Log In",
		alreadyAccount: "Already have an account?",
		enterEmail: "Enter your email",
		enterPassword: "Enter your password",
		enterName: "Enter your name",
	}, 
	miscelaneus: {
		loading: "Loading...",
		cancel: "Cancel",
		back: "Back",
		exit: "Exit",
		accept: "Accept",
		delete: "Delete",
		vehicleWord: "vehicle",
	}, 
	vehicleConfig: {
		title: "Vehicle configuration",
		vehicleBrand: "Vehicle brand",
		vehicleBrandPlaceholder: "Car's brand here",
		vehicleModel: "Vehicle model",
		vehicleModelPlaceholder: "Car's model here",
		vehicleNumPlate: "Number plate",
		vehicleNumPlatePlaceholder: "Car's number plate here",
		vehicleColor: "Vehicle Color",
		vehicleNickname: "Vehicle Nickname",
		vehicleNicknamePlaceholder: "Car's nickname here",
		continue: "Continue",
		notEV: "Don't have a vehicle to add?",
		cancel: "Cancel",
		skip: "Skip",
		customize: "Customize your",
		errorNumberPlate: "The numberplate already exists",
		defaultVehicle: "This vehicle is set as the default.",
	}, 
	profile: {
		yourVehicle: "Your Garage",
		changeVehicle: "Swipe to change your default vehicle",
		title: "Profile",
		vehicleNotDef: "Vehicle not defined yet",
		addNewVehicle: "Add a new vehicle",
		saveChanges: "Save changes",
		deleteVehicle: "Are you sure you want to delete your vehicle?",
		editProfile: "Edit your profile",
	}, 
	carInfoItem: {
		nickname: "Nickname:",
		numberPlate: "Number Plate:",
	}, 
	drawer: {
		home: "Home",
		profile: "Profile",
		settings: "Settings",
		tellAFriend: "Share it with a friend!",
		logOut: "Log Out",
		shareMessage: "Check EcoRoads out | An app to plan your Eco-Friendly trips efficiently.",
		achievements: "Achievements",
		report: "Report",
		help: "Help",
	}, 
	locationInfo: {
		mechanical: "Mechanical",
		electrical: "Electrical",
		freeSlots: "Free slots",
		getThere: "Get there!",
		likesNumber: "Likes",
		reportsNumber: "Reports",
		report: "Report",
		pollutionLevel: "Pollution:",
		shareStation: "Share",
		shareMessage: "Hey! Check out",
		shareMessage2: " station. Meet you there!",
	}, 
	uploadImage: {
		editImage: "Edit Image",
		uploadImage: "Upload Image",
	}, 
	achievementScreen: {
		subtitle: "Your achievements:",
		shareMessage: "I have completed this achievement on EcoRoads. Check it out: ",
		Achievements: {
			tellAFriendTitle: "Tell a friend!",
			tellAFriendDescription: "Share the app with a friend through the lateral menu to get this achievement.",
			firstRouteTitle: "Here we go!",
			firstRouteDescription: "Select a station on the map and choose 'Get There' to get this achievement.",
			fiveRoutesTitle: "Here we go!",
			fiveRoutesDescription: "Plan five routes with the application map to get this achievement.",
			twentyRoutesTitle: "Here we go!",
			twentyRoutesDescription: "Plan twenty routes with the application map to get this achievement.",
			firstSearchTitle: "Where to?",
			firstSearchDescription: "Search for a station through the top search bar in the map to get this achievement.",
			fiveSearchesTitle: "Where to?",
			fiveSearchesDescription: "Search for five stations through the top search bar in the map to get this achievement.",
			twentySearchesTitle: "Where to?",
			twentySearchesDescription: "Search for twenty stations through the top search bar in the map to get this achievement.",
			shareAStationTitle: "Meet you there!",
			shareAStationDescription: "Share a station with a friend by selecting it to get this achievement.",
			shareFiveStationsTitle: "Meet you there!",
			shareFiveStationsDescription: "Share five stations with a friend by selecting them to get this achievement.",
			shareTenStationsTitle: "Meet you there!",
			shareTenStationsDescription: "Share ten stations with a friend by selecting them to get this achievement.",
			setStationAsFavouriteTitle: "I choose you!",
			setStationAsFavouriteDescription: "Set a station as favourite by selecting it to get this achievement.",
			setThreeStationsAsFavouriteTitle: "I choose you!",
			setThreeStationsAsFavouriteDescription: "Set three stations as favourite by selecting them to get this achievement.",
			likeAStationTitle: "I like you, have a cupcake.",
			likeAStationDescription: "Like a station by selecting it to get this achievement.",
			likeFiveStationsTitle: "I like you, have a cupcake.",
			likeFiveStationsDescription: "Like five stations by selecting them to get this achievement.",
			likeTwentyStationsTitle: "I like you, have a cupcake.",
			likeTwentyStationsDescription: "Like twenty stations by selecting them to get this achievement.",
		}, 
	}, 
	report: {
		ReportApplicationScreen: {
			fillfields: "Please fill in all fields",
			OSversion: "Operating System",
			subjectinquiry: "Subject of Inquiry",
			detailsinquiry: "Details of Inquiry",
			title: "Report Screen",
			mobilepl: "Device type",
			type: "Type of Report ",
			smartphone: "Smartphone",
			tablet: "Tablet",
			ios: "iOS",
			android: "Android",
			bug: "Bug",
			generalHelp: "General help",
			featureRequest: "Feature request",
			feedback: "Feedback",
		}, 
		send: "Send",
		reportStation: {
			title: "Report a Station",
			subtitle: "",
			placeholder: "Issue description",
			poorCondition: "Poor conditions",
			badInformation: "Incorrect Info",
			dislike: "Dislike",
		}, 
	}, 
	achievementToast: {
		title: "Achievement completed!",
	}, 
	reportToast: {
		title: "Report sent",
		message: "Your report was sent successfully.",
		titleError: "Report not sent",
		messageError: "Your have already sent a report on this station.",
	}, 
	faq: {
		generalHelp: "General help",
		accountHelp: "Account help",
		whatIsEcoroads: "What is EcoRoads?",
		answerWhatIsEcoroads: "EcoRoads is personal mobility application, which puts at your disposal information and services to ease your electric vehicle traveling.",
		moreServicesEcoroads: "Will there be more services within EcoRoads?",
		answerMoreServicesEcoroads: "Yes, EcoRoads is an application under constant growth, always focused on delivering the best possible service.",
		isThereCost: "Is there any payment within EcoRoads?",
		answerIsThereCost: "The download and use of the application is completely free of charge.",
		personalizeMap: "Can I customize the map?",
		answerPersonalizeMap: "Yes, you can easily filter on the map the information of the charging points you want at any time. You can also add stations to your favorites section and filter the map based on them.",
		technicalIncidence: "What do I do if I have a technical issue?",
		answer1TechnicalIncidence: "If it is a technical issue related to a charging point, you can access the additional information mode of that station to report directly the problem you are experiencing.",
		answer2TechnicalIncidence: "If it is a technical issue of the application itself, you can access the reports section of the application, located in the side navigation bar, to report the information you see fit.",
		mandatorySignIn: "Do I need to register to use EcoRoads?",
		answerMandatorySignIn: "Without a user account you will not be able to access EcoRoads functionalities, therefore it is essential that you register.",
		safeData: "Is my personal data secure in the system?",
		answerSafeData: "Yes, all information is encrypted and meets the highest security standards.",
		howToDelete: "How do I delete my EcoRoads account?",
		answerHowToDelete: "You can do this from the app, in the settings section in the profile. By clicking on the 'Delete Account' button, all your information will be removed from the EcoRoads database.",
	}, 
	onboarding: {
		title1: "Welcome to Ecoroads",
		subtitle1: "The app to plan your Eco-Friendly trips efficiently",
		title2: "Customize your profile",
		subtitle2: "Add your vehicles and change their color to your liking",
		title3: "Create easy-to-follow routes",
		subtitle3: "And get redirected if your EV's battery is too low",
		title4: "Check the availability",
		subtitle4: "Know the status of any station in real time",
		title5: "Obtain achievements",
		subtitle5: "And share them with your friends to brag about it",
		skip: "Skip",
		next: "Next",
		done: "Done",
	}, 
	warningToast: {
		title: "Beware of pollution",
		message: "This destination has a pollution of",
	}, 
	help: {
		chat: "Chat",
		faq: "FAQs",
		title: "Help section",
		tutorial: "Tutorial",
	}, 
	autonomyModal: {
		title: "Do you want to introduce your vehicle's autonomy?",
		placeholder: "Your autonomy in km",
	}, 
	editProfile: {
		title: "Profile updated",
		message: "The changes have been saved correctly",
	}
}
export{ en }