const es = {
	home: {
		title: "Inicio",
		bottomBar: {
			map: "Mapa",
			vehicle: "Vehículo",
			bike: "Bici",
			favs: "Favoritos",
			highlight: "Destacados",
		}, 
		searchBar: "Buscar:",
		car: "Coche",
		bike: "Bicicleta",
		foot: "A pie",
		time: "Tiempo estimado",
		distance: "Distancia",
		routeOptions: "Opciones de ruta",
	}, 
	settings: {
		title: "Ajustes",
		subtitle: "Bienvenido a los ajustes",
		logOut: "Cerrar sesión",
		setEN: "Inglés",
		setCAT: "Catalán",
		setES: "Español",
		deleteAccount: "Borrar tu cuenta",
		deleteAccountTitle: "¿Estás seguro de que quieres eliminar tu cuenta?",
		deleteAccountSubtitle: "Esta acción no es reversible y perderás todo acceso futuro a la aplicación.",
		setLanguage: "Escoger idioma",
		confirmDeleteAccount: "Para eliminar tu cuenta debes escribir debajo tu nombre de usuario",
	}, 
	signIn: {
		title: "Iniciar sesión",
		form: {
			enterCredentials: "Ingrese sus credenciales",
		}, 
		otherSocial: "O inicie sesión con",
		pwdOrEmailMessage: "Hay un error con el email o contraseña",
		emptyFieldMessage: "Porfavor rellene todos los campos",
		banMessage: "Este usuario está vetado de la app",
		noAccount: "¿No tiene una cuenta?",
		enterEmail: "Ingrese su email",
		enterPassword: "Ingrese su contraseña",
	}, 
	signUp: {
		title: "Registrarse",
		form: {
			enterCredentials: "Ingrese sus credenciales",
			email: "Email:",
			password: "Contraseña:",
			name: "Nombre:",
		}, 
		goToSignIn: "Ir a Iniciar sesión",
		alreadyAccount: "¿Ya tiene cuenta?",
		enterEmail: "Ingrese su email",
		enterPassword: "Ingrese su contraseña",
		enterName: "Ingrese su nombre",
	}, 
	miscelaneus: {
		loading: "Cargando...",
		cancel: "Cancelar",
		back: "Atrás",
		exit: "Salir",
		accept: "Aceptar",
		delete: "Eliminar",
		vehicleWord: "vehículo",
	}, 
	vehicleConfig: {
		title: "Configuracion del vehículo",
		vehicleBrand: "Marca del vehículo",
		vehicleBrandPlaceholder: "Introduce la marca",
		vehicleModel: "Modelo del vehículo",
		vehicleModelPlaceholder: "Introduce el modelo",
		vehicleNumPlate: "Matrícula",
		vehicleNumPlatePlaceholder: "Introduce la matrícula",
		vehicleColor: "Color del vehículo",
		vehicleNickname: "Apodo del vehículo",
		vehicleNicknamePlaceholder: "Introduce el apodo",
		continue: "Continuar",
		notEV: "¿No tienes un vehiculo para añadir?",
		cancel: "Cancelar",
		skip: "Saltar",
		customize: "Personaliza tu",
		errorNumberPlate: "La matrícula ya existe",
		defaultVehicle: "Este vehículo está marcado como predeterminado.",
	}, 
	profile: {
		yourVehicle: "Tu garaje",
		changeVehicle: "Desliza para cambiar tu vehículo por defecto",
		title: "Perfil",
		vehicleNotDef: "Vehículo no definido",
		addNewVehicle: "Añade un vehículo",
		saveChanges: "Guardar cambios",
		deleteVehicle: "¿Estás seguro de que quieres eliminar tu vehículo?",
		editProfile: "Edita tu perfil",
	}, 
	carInfoItem: {
		nickname: "Apodo:",
		numberPlate: "Matricula:",
	}, 
	drawer: {
		home: "Inicio",
		profile: "Perfil",
		settings: "Ajustes",
		tellAFriend: "¡Compártelo con un amigo!",
		logOut: "Cerrar sesión",
		shareMessage: "Descubre EcoRoads | Una aplicación para planear tus viajes 'Eco-Friendly' de forma eficiente.",
		achievements: "Logros",
		report: "Reporte",
		help: "Ayuda",
	}, 
	locationInfo: {
		mechanical: "Mecánicas",
		electrical: "Eléctricas",
		freeSlots: "Espacios libres",
		getThere: "¡Llévame!",
		likesNumber: "Me gustas",
		reportsNumber: "Reportes",
		report: "Reportar",
		pollutionLevel: "Contaminación:",
		shareStation: "Compartir",
		shareMessage: "Ey! Echa un vistazo a",
		shareMessage2: ". Nos vemos ahí!",
	}, 
	uploadImage: {
		editImage: "Editar Imagen",
		uploadImage: "Añadir Imagen",
	}, 
	achievementScreen: {
		subtitle: "Tus logros:",
		shareMessage: "He completado este logro en EcoRoads. Échale un vistazo: ",
		Achievements: {
			tellAFriendTitle: "¡Díselo a un amigo!",
			tellAFriendDescription: "Comparte la app con un amigo mediante el menú lateral para obtener este logro.",
			firstRouteTitle: "¡Allá vamos!",
			firstRouteDescription: "Selecciona una estación en el mapa y clica en '¡Llévame!' para obtener este logro.",
			fiveRoutesTitle: "¡Allá vamos!",
			fiveRoutesDescription: "Planea cinco rutas con el mapa de la aplicación para obtener este logro.",
			twentyRoutesTitle: "¡Allá vamos!",
			twentyRoutesDescription: "Planea veinte rutas con el mapa de la aplicación para obtener este logro.",
			firstSearchTitle: "¿Dónde vamos?",
			firstSearchDescription: "Busca una estación con la barra de búsqueda del mapa para obtener este logro.",
			fiveSearchesTitle: "¿Dónde vamos?",
			fiveSearchesDescription: "Busca cinco estaciones con la barra de búsqueda del mapa para obtener este logro.",
			twentySearchesTitle: "¿Dónde vamos?",
			twentySearchesDescription: "Busca veinte estaciones con la barra de búsqueda del mapa para obtener este logro.",
			shareAStationTitle: "¡Nos vemos allí!",
			shareAStationDescription: "Comparte una estación con un amigo tras seleccionarla para obtener este logro.",
			shareFiveStationsTitle: "¡Nos vemos allí!",
			shareFiveStationsDescription: "Comparte cinco estaciones con un amigo tras seleccionarlas para obtener este logro.",
			shareTenStationsTitle: "¡Nos vemos allí!",
			shareTenStationsDescription: "Comparte diez estaciones con un amigo tras seleccionarlas para obtener este logro.",
			setStationAsFavouriteTitle: "¡Te escojo a tí!",
			setStationAsFavouriteDescription: "Selecciona una estación como favorita tras seleccionarla para obtener este logro.",
			setThreeStationsAsFavouriteTitle: "¡Te escojo a tí!",
			setThreeStationsAsFavouriteDescription: "Selecciona tres estaciones como favoritas tras seleccionarlas para obtener este logro.",
			likeAStationTitle: "Me gustas, toma una galleta.",
			likeAStationDescription: "Dale me gusta a una estación tras seleccionarla para obtener este logro.",
			likeFiveStationsTitle: "Me gustas, toma una galleta.",
			likeFiveStationsDescription: "Dale me gusta a cinco estaciones tras seleccionarlas para obtener este logro.",
			likeTwentyStationsTitle: "Me gustas, toma una galleta.",
			likeTwentyStationsDescription: "Dale me gusta a veinte estaciones tras seleccionarlas para obtener este logro.",
		}, 
	}, 
	report: {
		ReportApplicationScreen: {
			fillfields: "Porfavor rellena todos los campos",
			OSversion: "Sistema Operativo",
			subjectinquiry: "Tema de consulta",
			detailsinquiry: "Detalles de la consulta",
			title: "Pagina de Reporte",
			mobilepl: "Tipo de dispositivo",
			type: "Tipo de Reporte",
			smartphone: "Smartphone",
			tablet: "Tablet",
			ios: "iOS",
			android: "Android",
			bug: "Bug",
			generalHelp: "Ayuda general",
			featureRequest: "Solicitud de funcionalidad",
			feedback: "Comentario",
		}, 
		send: "Enviar",
		reportStation: {
			title: "Reportar una estación",
			subtitle: "",
			placeholder: "Descripción del problema",
			poorCondition: "Malas condiciones",
			badInformation: "Información erronea",
			dislike: "No me gusta",
		}, 
	}, 
	achievementToast: {
		title: "¡Logro completado!",
	}, 
	reportToast: {
		title: "Reporte enviado",
		message: "Tu reporte ha sido correctamente enviado.",
		titleError: "Reporte no enviado",
		messageError: "Ya has enviado un reporte a esta estación.",
	}, 
	faq: {
		generalHelp: "Ayuda general",
		accountHelp: "Ayuda de cuenta",
		whatIsEcoroads: "¿Qué es EcoRoads?",
		answerWhatIsEcoroads: "EcoRoads es una aplicación de movilidad personal, que pone a tu disposición información y servicios para facilitar tus viajes usando vehículos eléctricos.",
		moreServicesEcoroads: "¿Habrá más servicios dentro de EcoRoads?",
		answerMoreServicesEcoroads: "Sí, EcoRoads es una aplicación que estará en constante crecimiento, con el fin de poder ofrecer en todo momento el mejor servicio posible.",
		isThereCost: "¿Tiene algun coste utilizar EcoRoads?",
		answerIsThereCost: "La descarga y el uso de la aplicación és completamente gratuito.",
		personalizeMap: "¿Puedo personalizar el mapa?",
		answerPersonalizeMap: "Sí, puedes filtrar fácilmente en el mapa la información de los puntos de carga que quieras en todo momento. Además puedes añadir estaciones a tu sección de favoritos y filtrar el mapa en base a estos.",
		technicalIncidence: "¿Qué hago si tengo una incidencia técnica?",
		answer1TechnicalIncidence: "Si se trata de una incidencia técnica relacionada con algún punto de carga, puedes acceder al modal de información adicional de esa estación para reportar directamente el problema que tengas.",
		answer2TechnicalIncidence: "Si se trata de una incidencia técnica de la propia aplicación, puedes acceder a la sección de reportes de la aplicación, situada en la barra de navegación lateral, para reportar la información que veas conveniente.",
		mandatorySignIn: "¿Es necesario registrarse para utilizar EcoRoads?",
		answerMandatorySignIn: "Sin una cuenta de usuario no podrás acceder a las funcionalidades de EcoRoads, por lo tanto es imprescindible que te registres.",
		safeData: "¿Están seguros mis datos personales en el sistema?",
		answerSafeData: "Sí, toda la información está encriptada y cumple con los estándares de seguridad más exigentes.",
		howToDelete: "¿Cómo doy de baja mi cuenta en EcoRoads?",
		answerHowToDelete: "Lo puedes hacer desde la app, en la sección de configuración en el perfil. Pulsando en el botón de 'Eliminar Cuenta', toda tu información se eliminará de la base de datos de EcoRoads.",
	}, 
	onboarding: {
		title1: "Bienvenido a Ecoroads",
		subtitle1: "La aplicación para planear tus viajes 'Eco-Friendly' de forma eficiente",
		title2: "Personaliza tu perfil",
		subtitle2: "Añade tus vehículos y cambia su color a tu parecer",
		title3: "Crea rutas fáciles de seguir",
		subtitle3: "Descubre rutas que se ajustan a tu autonomía",
		title4: "Consulta la disponibilidad",
		subtitle4: "Conoce el estado de cualquier estación en tiempo real",
		title5: "Obtén logros",
		subtitle5: "Y compartelos con tus amigos para fardar de ello",
		skip: "Saltar",
		next: "Siguiente",
		done: "Finalizar",
	}, 
	warningToast: {
		title: "Cuidado con la contaminación",
		message: "Este destino tiene una contaminación de",
	}, 
	help: {
		chat: "Chat",
		faq: "FAQs",
		title: "Sección de ayuda",
		tutorial: "Tutorial",
	}, 
	autonomyModal: {
		title: "¿Quieres introducir la autonomía de tu vehículo?",
		placeholder: "Tu autonomía en km",
	}, 
	editProfile: {
		title: "Perfil actualizado",
		message: "Los cambios se han guardado correctamente",
	}
}
export{ es }